### ISSUE TITLE
Use C++ header files instead of C

### ISSUE THREAD

**Issue by kevinaboos** [jianding17/Agora#180]
The most problematic one is the usage of `#include <complex.h>`; we need to use `include <complex>` instead. 
The reason for this is that the `complex.h` C-style header file performs a global `#define I ...` which breaks the compilation multiple other libraries, primarily some Boost libraries. 

Other C-style header includes should be transformed to use the C++-style headers too, though those are lower priority.

**Comment by asedlmayr** [comment]
Merged into develop
